'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer_Address
    Public Property Customer_Address_Id As Integer
    Public Property Address_Id As Integer
    Public Property Address_Type_Id As Integer
    Public Property Customer_Id As Integer

    Public Overridable Property Address As Address 
    Public Overridable Property Address_Type As Address_Type
    Public Overridable Property Customer As Customer

End Class
