'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property Customer_Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property BrithDate As Nullable(Of Date)
    Public Property Addresses As List(Of Address)

    Public Overridable Property Customer_Address As ICollection(Of Customer_Address) = New HashSet(Of Customer_Address)

End Class
