'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property Address_Id As Integer
    Public Property Line1 As String
    Public Property Line2 As String
    Public Property City As String
    Public Property Province As String
    Public Property Country As String
    Public Property ZipCode As Nullable(Of Integer)

    Public Overridable Property Customer_Address As ICollection(Of Customer_Address) = New HashSet(Of Customer_Address)

End Class
