'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SimpleCrudTestEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SimpleCrudTestEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property Address_Type() As DbSet(Of Address_Type)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Customer_Address() As DbSet(Of Customer_Address)

End Class
